path: M:\Projects\CV\Key_Point_Detection\dataset # dataset root dir
train: train  # train images (relative to 'path') 4 images
val: val  # val images (relative to 'path') 4 images

kpt_shape: [24, 3] 

names:
  0: groenendael
  1: Chihuahua
  2: Tibetan_mastiff
  3: Bouvier_des_Flandres
  4: Irish_terrier
  5: Dandie_Dinmont
  6: Doberman
  7: bloodhound
  8: Chesapeake_Bay_retriever
  9: basenji
  10: borzoi
  11: Labrador_retriever
  12: Newfoundland
  13: Scotch_terrier
  14: English_foxhound
  15: Welsh_springer_spaniel
  16: silky_terrier
  17: Eskimo_dog
  18: Saluki
  19: toy_terrier
  20: cocker_spaniel
  21: flat-coated_retriever
  22: Tibetan_terrier
  23: Kerry_blue_terrier
  24: Rhodesian_ridgeback
  25: Yorkshire_terrier
  26: Blenheim_spaniel
  27: Irish_water_spaniel
  28: EntleBucher
  29: English_springer
  30: German_shepherd
  31: Old_English_sheepdog
  32: Gordon_setter
  33: American_Staffordshire_terrier
  34: black-and-tan_coonhound
  35: boxer
  36: Bernese_mountain_dog
  37: Weimaraner
  38: Brittany_spaniel
  39: French_bulldog
  40: miniature_poodle
  41: cairn
  42: giant_schnauzer
  43: Shetland_sheepdog
  44: Border_collie
  45: Saint_Bernard
  46: basset
  47: Norwich_terrier
  48: Rottweiler
  49: standard_schnauzer
  50: malinois
  51: Mexican_hairless
  52: komondor
  53: kelpie
  54: Maltese_dog
  55: curly-coated_retriever
  56: wire-haired_fox_terrier
  57: Siberian_husky
  58: Irish_wolfhound
  59: soft-coated_wheaten_terrier
  60: vizsla
  61: Border_terrier
  62: collie
  63: schipperke
  64: toy_poodle
  65: Samoyed
  66: Airedale
  67: Lakeland_terrier
  68: redbone
  69: Australian_terrier
  70: African_hunting_dog
  71: Japanese_spaniel
  72: beagle
  73: West_Highland_white_terrier
  74: bull_mastiff
  75: Lhasa
  76: chow
  77: malamute
  78: dhole
  79: Boston_bull
  80: briard
  81: Norfolk_terrier
  82: Irish_setter
  83: papillon
  84: otterhound
  85: Walker_hound
  86: Cardigan
  87: Pekinese
  88: miniature_pinscher
  89: Italian_greyhound
  90: Greater_Swiss_Mountain_dog
  91: Shih-Tzu
  92: Brabancon_griffon
  93: Appenzeller
  94: keeshond
  95: Sealyham_terrier
  96: Pembroke
  97: Staffordshire_bullterrier
  98: affenpinscher
  99: standard_poodle
  100: German_short-haired_pointer
  101: Sussex_spaniel
  102: Scottish_deerhound
  103: Afghan_hound
  104: golden_retriever
  105: Leonberg
  106: Pomeranian
  107: kuvasz
  108: whippet
  109: pug
  110: Ibizan_hound
  111: Norwegian_elkhound
  112: Great_Pyrenees
  113: Bedlington_terrier
  114: clumber
  115: miniature_schnauzer
  116: bluetick
  117: dingo
  118: Great_Dane
  119: English_setter